### ISSUE TITLE
Generator script

### ISSUE THREAD

**Issue by musjj** [decaycs/decay-gtk#1]
It would be nice to have a script that can generate these themes.
Something like: https://github.com/catppuccin/gtk
I assume that you're using a base instead of writing these from a scratch, so you can just turn whatever workflow you used to make these into a script.

My use case is that I wanted to have decayce with the cosmic background color.
I find decayce's background colors too desaturated and black. On the other hand, cosmic's theme feels a bit too washed out overall, but the tonality of the background color feels just right.

**Comment by musjj** [comment]
Also, do you have the wallpaper in the repo's screenshot? Can't find it in your wallpaper repo.

**Comment by Alxhr0** [comment]
Since Decay-GTK is created using Gradience, creating scripts for changing the colors in the theme isn't needed since Grapejuice allows the user to modify the theme and colors how the users please.

**Comment by musjj** [comment]
Can you link to the grapejuice repo? I looked around, but the only grapejuice I can find is a wine+roblox management application.
